# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 901, 424))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputSection = QtWidgets.QVBoxLayout()
        self.inputSection.setObjectName("inputSection")
        self.input_section_header = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_section_header.setFont(font)
        self.input_section_header.setObjectName("input_section_header")
        self.inputSection.addWidget(self.input_section_header)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.nameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_8.addWidget(self.nameLabel)
        self.nameField = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.nameField.setObjectName("nameField")
        self.horizontalLayout_8.addWidget(self.nameField)
        self.inputSection.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.grammarLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grammarLabel.sizePolicy().hasHeightForWidth())
        self.grammarLabel.setSizePolicy(sizePolicy)
        self.grammarLabel.setObjectName("grammarLabel")
        self.horizontalLayout_7.addWidget(self.grammarLabel)
        self.saveGrammarButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveGrammarButton.setObjectName("saveGrammarButton")
        self.horizontalLayout_7.addWidget(self.saveGrammarButton)
        self.inputSection.addLayout(self.horizontalLayout_7)
        self.grammarText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.grammarText.setPlainText("")
        self.grammarText.setObjectName("grammarText")
        self.inputSection.addWidget(self.grammarText)
        self.infoLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.inputSection.addWidget(self.infoLabel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.leftRecursionButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.leftRecursionButton.setObjectName("leftRecursionButton")
        self.gridLayout.addWidget(self.leftRecursionButton, 0, 0, 1, 1)
        self.fatoradaButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.fatoradaButton.setObjectName("fatoradaButton")
        self.gridLayout.addWidget(self.fatoradaButton, 0, 1, 1, 1)
        self.firstButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.firstButton.setObjectName("firstButton")
        self.gridLayout.addWidget(self.firstButton, 1, 0, 1, 1)
        self.followButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.followButton.setObjectName("followButton")
        self.gridLayout.addWidget(self.followButton, 1, 1, 1, 1)
        self.inputSection.addLayout(self.gridLayout)
        self.glcPropriaButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.glcPropriaButton.setObjectName("glcPropriaButton")
        self.inputSection.addWidget(self.glcPropriaButton)
        self.horizontalLayout.addLayout(self.inputSection)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.resultsLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultsLabel.setFont(font)
        self.resultsLabel.setObjectName("resultsLabel")
        self.verticalLayout_5.addWidget(self.resultsLabel)
        self.resultText_1 = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.resultText_1.setObjectName("resultText_1")
        self.verticalLayout_5.addWidget(self.resultText_1)
        self.resultText_2 = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.resultText_2.setPlainText("")
        self.resultText_2.setObjectName("resultText_2")
        self.verticalLayout_5.addWidget(self.resultText_2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.grammarListBox = QtWidgets.QVBoxLayout()
        self.grammarListBox.setContentsMargins(0, -1, -1, -1)
        self.grammarListBox.setObjectName("grammarListBox")
        self.listLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.listLabel.setFont(font)
        self.listLabel.setObjectName("listLabel")
        self.grammarListBox.addWidget(self.listLabel)
        self.grammarList = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.grammarList.setObjectName("grammarList")
        self.grammarListBox.addWidget(self.grammarList)
        self.horizontalLayout.addLayout(self.grammarListBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gramáticas Livres de Contexto"))
        self.input_section_header.setText(_translate("MainWindow", "<html><head/><body><p>Criar Nova Gramática</p></body></html>"))
        self.nameLabel.setText(_translate("MainWindow", "Nome"))
        self.grammarLabel.setText(_translate("MainWindow", "Gramática"))
        self.saveGrammarButton.setText(_translate("MainWindow", "Salvar Gramática"))
        self.leftRecursionButton.setText(_translate("MainWindow", "Recursão a Esquerda"))
        self.fatoradaButton.setText(_translate("MainWindow", "Fatorada"))
        self.firstButton.setText(_translate("MainWindow", "First"))
        self.followButton.setText(_translate("MainWindow", "Follow"))
        self.glcPropriaButton.setText(_translate("MainWindow", "GLC Própria"))
        self.resultsLabel.setText(_translate("MainWindow", "<html><head/><body><p>Resultados</p></body></html>"))
        self.listLabel.setText(_translate("MainWindow", "Gramáticas Geradas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

