# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 541, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.regex_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.regex_label.setObjectName("regex_label")
        self.gridLayout_2.addWidget(self.regex_label, 0, 0, 1, 1)
        self.regex_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.regex_input.setObjectName("regex_input")
        self.gridLayout_2.addWidget(self.regex_input, 0, 1, 1, 1)
        self.regex_to_fa_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.regex_to_fa_button.setObjectName("regex_to_fa_button")
        self.gridLayout_2.addWidget(self.regex_to_fa_button, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 109, 541, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 521, 196))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.rg_text = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.rg_text.setObjectName("rg_text")
        self.gridLayout.addWidget(self.rg_text, 2, 1, 1, 1)
        self.fa_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fa_label.setObjectName("fa_label")
        self.gridLayout.addWidget(self.fa_label, 1, 0, 1, 1)
        self.determinize_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.determinize_button.setObjectName("determinize_button")
        self.gridLayout.addWidget(self.determinize_button, 3, 0, 1, 1)
        self.rg_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rg_label.setObjectName("rg_label")
        self.gridLayout.addWidget(self.rg_label, 1, 1, 1, 1)
        self.transition_table = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.transition_table.setMaximumSize(QtCore.QSize(16777215, 257))
        self.transition_table.setObjectName("transition_table")
        self.transition_table.setColumnCount(0)
        self.transition_table.setRowCount(0)
        self.gridLayout.addWidget(self.transition_table, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.minimize_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minimize_button.setObjectName("minimize_button")
        self.gridLayout.addWidget(self.minimize_button, 4, 0, 1, 1)
        self.rg_to_fa_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.rg_to_fa_button.setObjectName("rg_to_fa_button")
        self.gridLayout.addWidget(self.rg_to_fa_button, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 541, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.test_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.test_button.setObjectName("test_button")
        self.horizontalLayout_3.addWidget(self.test_button)
        self.word_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.word_input.setObjectName("word_input")
        self.horizontalLayout_3.addWidget(self.word_input)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.menuFile.addAction(self.actionSalvar)
        self.menuFile.addAction(self.actionAbrir)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Linguagens Regulares"))
        self.regex_label.setText(_translate("MainWindow", "Expressão Regular"))
        self.regex_to_fa_button.setText(_translate("MainWindow", "Converter para AF"))
        self.fa_label.setText(_translate("MainWindow", "Autômato"))
        self.determinize_button.setText(_translate("MainWindow", "Determinizar"))
        self.rg_label.setText(_translate("MainWindow", "Gramática"))
        self.minimize_button.setText(_translate("MainWindow", "Minimizar"))
        self.rg_to_fa_button.setText(_translate("MainWindow", "Converter para AF"))
        self.test_button.setText(_translate("MainWindow", "Testar Sentença"))
        self.menuFile.setTitle(_translate("MainWindow", "Arquivo"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar AF"))
        self.actionAbrir.setText(_translate("MainWindow", "Importar AF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

